# Generated by Django 4.1.7 on 2023-03-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_remove_anime_translated_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('rank', 'popularity', 'mean')},
        ),
    ]
