# Generated by Django 4.2 on 2023-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_anime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
