# Generated by Django 4.2 on 2023-04-20 11:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='background',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='pictures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='related_anime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='related_manga',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
