# Generated by Django 4.2 on 2023-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_anime_background_anime_pictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mal_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
